version: "3.7"

services:
  database:
    image: mariadb:latest
    container_name: consumer_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=consumer
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./volumes/database:/var/lib/mysql
      - ./volumes/sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    container_name: consumer_app
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge